name: Build Dockerfile
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.8'

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          # cache: yarn
          # cache-dependency-path: 'ui'

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Prebuild binaries
        working-directory: cmd/keel
        run: |
          wget -q -P ~ https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xvf ~/aarch64-linux-musl-cross.tgz -C ~ > /dev/null

          # Only the basic flags for now
          LDFLAGS="-X github.com/keel-hq/keel/version.Version=$GITHUB_REF "
          LDFLAGS+="-X github.com/keel-hq/keel/version.Revision=${GITHUB_SHA::7} "
          LDFLAGS+="-X github.com/keel-hq/keel/version.BuildDate=$(date -u +%Y-%m-%dT%H%M%SZ)"

          CGO_ENABLED=1 GOARCH=arm64 GOOS=linux CC=~/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc go build -ldflags="$LDFLAGS" -o release/keel-linux-arm64
          CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -ldflags="$LDFLAGS" -o release/keel-linux-amd64

      - run: yarn install
        working-directory: ui
      - run: yarn run build
        working-directory: ui
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:main
          cache-to: type=inline
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
