name: Build Dockerfile
on:
  push:
    branches:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.8'

      - name: Prebuild binaries
        working-directory: cmd/keel
        run: |
          # Only the basic flags for now
          LDFLAGS="-X github.com/keel-hq/keel/version.Version=$(git describe --tags --abbrev=0) "
          LDFLAGS+="-X github.com/keel-hq/keel/version.Revision=$(git rev-parse --short HEAD) "
          LDFLAGS+="-X github.com/keel-hq/keel/version.BuildDate=$(date -u +%Y-%m-%dT%H%M%SZ)"

          # GOARCH=arm GOOS=linux go build -ldflags="$LDFLAGS" -o release/keel-linux-arm
          GOARCH=arm64 GOOS=linux go build -ldflags="$LDFLAGS" -o release/keel-linux-arm64
          GOARCH=amd64 GOOS=linux go build -ldflags="$LDFLAGS" -o release/keel-linux-amd64

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: yarn
      - run: yarn install
        working-directory: ui
      - run: yarn run build
        working-directory: ui
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:main
          cache-to: type=inline
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            owner_type: user
            untagged_only: true
